export const Hobbies =[
    { text: "3D Modeling", emoji: "🖥️" },
    { text: "Acting", emoji: "🎭" },
    { text: "Aerobics", emoji: "👟" },
    { text: "Air hockey", emoji: "🏑" },
    { text: "Airsoft", emoji: "🔫" },
    { text: "American football", emoji: "🏈" },
    { text: "Animal care", emoji: "🐕" },
    { text: "Animals", emoji: "🐈" },
    { text: "Antiquing", emoji: "🏺" },
    { text: "Aquarium", emoji: "🐠" },
    { text: "Arcade Games", emoji: "🕹️" },
    { text: "Archaeology", emoji: "🏺" },
    { text: "Archery", emoji: "🏹" },
    { text: "Architecture", emoji: "📐" },
    { text: "Artwork ", emoji: "🎨" },
    { text: "Association football", emoji: "🏈" },
    { text: "Astrology", emoji: "♓" },
    { text: "Astronomy", emoji: "🔭" },
    { text: "Auto racing", emoji: "🏎️" },
    { text: "Automotive repair", emoji: "🏎️" },
    { text: "BMX", emoji: "🏍️" },
    { text: "Badminton", emoji: "🏸" },
    { text: "Baking", emoji: "🍕" },
    { text: "Ballet", emoji: "🩰" },
    { text: "Ballet Dancing", emoji: "💃" },
    { text: "Ballooning", emoji: "🎈" },
    { text: "Baseball", emoji: "⚾️" },
    { text: "Basketball", emoji: "🏀" },
    { text: "Volleyball", emoji: "🏐" },
    { text: "Beachcombing", emoji: "🚂" },
    { text: "Beatboxing", emoji: "🗣️" },
    { text: "Bicycling", emoji: "🚲" },
    { text: "Billiards", emoji: "🎱" },
    { text: "Blogging", emoji: "💻" },
    { text: "Board games", emoji: "🕹️" },
    { text: "Board sports", emoji: "🏄" },
    { text: "Boating", emoji: "⛵" },
    { text: "Body Building", emoji: "🏋" },
    { text: "Book collecting", emoji: "📕" },
    { text: "Bowling", emoji: "🎳" },
    { text: "Boxing", emoji: "🥊" },
    { text: "jiu-jitsu", emoji: "🥋" },
    { text: "Butterfly Watching", emoji: "🦋" },
    { text: "Cake Decorating", emoji: "🍰" },
    { text: "Calligraphy", emoji: "📝" },
    { text: "Camping", emoji: "⛺" },
    { text: "Candle making", emoji: "🕯" },
    { text: "Car Racing", emoji: "🏎️" },
    { text: "Cartooning", emoji: "🐼" },
    { text: "Casino Gambling", emoji: "🎰" },
    { text: "Ceramics", emoji: "🍶" },
    { text: "Chess", emoji: "♛" },
    { text: "Cigar Smoking", emoji: "🚭" },
    { text: "Climbing", emoji: "🏔️" },
    { text: "Cloud Watching", emoji: "🌥️" },
    { text: "Coffee Roasting", emoji: "☕" },
    { text: "Sneaker Collecting", emoji: "👟" },
    { text: "Collecting Antiques", emoji: "🏺" },
    { text: "Collecting Artwork", emoji: "🖌️" },
    { text: "Collecting Music Albums", emoji: "💿" },
    { text: "Coloring", emoji: "🎨" },
    { text: "Comic book collecting", emoji: "📕" },
    { text: "Compose Music", emoji: "🎼" },
    { text: "Computer", emoji: "💻" },
    { text: "Programming", emoji: "💻" },
    { text: "Coding", emoji: "💻" },
    { text: "Conworlding", emoji: "🤝" },
    { text: "Cooking", emoji: "🍳" },
    { text: "Cosplay", emoji: "👗" },
    { text: "Crafts", emoji: "⛵" },
    { text: "Cricket", emoji: "🏏" },
    { text: "Crochet", emoji: "🧶" },
    { text: "Crossbow", emoji: "🏹" },
    { text: "Curling", emoji: "🥌" },
    { text: "Cycling", emoji: "🚲" },
    { text: "DVD", emoji: "💿" },
    { text: "Dance", emoji: "💃" },
    { text: "Dancing", emoji: "💃" },
    { text: "Deep Sea Fishing", emoji: "🐠" },
    { text: "Digital Photography", emoji: "📷" },
    { text: "Digital arts", emoji: "📷" },
    { text: "Dolls", emoji: "🎎" },
    { text: "Drama", emoji: "🎭" },
    { text: "Drawing", emoji: "🎨" },
    { text: "Driving", emoji: "🏎️" },
    { text: "Eating", emoji: "🍕" },
    { text: "Embroidery", emoji: "🧶" },
    { text: "Entertaining", emoji: "🍿" },
    { text: "Equestrianism", emoji: "🐎" },
    { text: "Exercise", emoji: "👟" },
    { text: "Extreme Sports", emoji: "👟" },
    { text: "Figure skating", emoji: "⛸️" },
    { text: "Fishing", emoji: "🎣" },
    { text: "Floral Arrangements", emoji: "🌼" },
    { text: "Flying", emoji: "✈️" },
    { text: "Football", emoji: "⚽" },
    { text: "Foreign language learning", emoji: "🌐" },
    { text: "Learning English", emoji: "🌐" },
    { text: "Learning Arabic", emoji: "🌐" },
    { text: "Learning Hindi", emoji: "🌐" },
    { text: "Learning German", emoji: "🌐" },
    { text: "Learning Spanish", emoji: "🌐" },
    { text: "Learning Japanese", emoji: "🌐" },
    { text: "Learning Chinese", emoji: "🌐" },
    { text: "Fossil hunting", emoji: "🏺" },
    { text: "Gambling", emoji: "🎲" },
    { text: "Gaming", emoji: "🎮" },
    { text: "Gardening", emoji: "🌻" },
    { text: "Ghost hunting", emoji: "👟" },
    { text: "Golfing", emoji: "⛳" },
    { text: "Guitar", emoji: "🎸" },
    { text: "Gunsmithing", emoji: "🎨" },
    { text: "Gymnastics", emoji: "👟" },
    { text: "Hiking", emoji: "🏔️" },
    { text: "Horse riding", emoji: "🐎" },
    { text: "Hunting", emoji: "👟" },
    { text: "Ice hockey", emoji: "🏒" },
    { text: "Ice skating", emoji: "⛸️" },
    { text: "Jewelry Making", emoji: "🏺" },
    { text: "Jigsaw Puzzles", emoji: "🧩" },
    { text: "Jogging", emoji: "👟" },
    { text: "Judo", emoji: "🥋" },
    { text: "Jump Roping", emoji: "👟" },
    { text: "Kite Boarding", emoji: "🪁" },
    { text: "Knife making", emoji: "🗡️" },
    { text: "Knife throwing", emoji: "🗡️" },
    { text: "Knitting", emoji: "🧶" },
    { text: "Leather crafting", emoji: "💼" },
    { text: "Lego building", emoji: "🎮" },
    { text: "Legos", emoji: "🎮" },
    { text: "Music", emoji: "🎵" },
    { text: "Machining", emoji: "⚙️" },
    { text: "Magic", emoji: "🎩" },
    { text: "Martial arts", emoji: "🥋" },
    { text: "Meditation", emoji: "🧘🏻" },
    { text: "Metal detecting", emoji: "⚙️" },
    { text: "Meteorology", emoji: "🌥️" },
    { text: "Microscopy", emoji: "🔭" },
    { text: "Model", emoji: "💃" },
    { text: "Motorcycles", emoji: "🏍️" },
    { text: "Listening to Music", emoji: "🎧" },
    { text: "Nail Art", emoji: "💅" },
    { text: "Origami", emoji: "🔖" },
    { text: "Paintball", emoji: "🌑" },
    { text: "Painting", emoji: "🎨" },
    { text: "Parachuting", emoji: "🪂" },
    { text: "Parkour", emoji: "👟" },
    { text: "Photography", emoji: "📷" },
    { text: "Smoking", emoji: "🚭" },
    { text: "Playing musical instruments", emoji: "🎵" },
    { text: "Poker", emoji: "🃏" },
    { text: "Pole Dancing", emoji: "💃" },
    { text: "Pottery", emoji: "🏺" },
    { text: "Puzzles", emoji: "🧩" },
    { text: "R/C Boats", emoji: "🕹️" },
    { text: "R/C Cars", emoji: "🕹️" },
    { text: "R/C Helicopters", emoji: "🕹️" },
    { text: "R/C Planes", emoji: "🕹️" },
    { text: "Rafting", emoji: "🛶" },
    { text: "Rapping", emoji: "🗣️" },
    { text: "Reading", emoji: "📖" },
    { text: "Relaxing", emoji: "🏖️" },
    { text: "Robotics", emoji: "🤖" },
    { text: "Rockets", emoji: "🚀" },
    { text: "Roleplaying", emoji: "🎭" },
    { text: "Running", emoji: "👟" },
    { text: "Sailing", emoji: "⛵" },
    { text: "Scuba Diving", emoji: "🤿" },
    { text: "Sculpting", emoji: "🔨" },
    { text: "Sculpture", emoji: "🔨" },
    { text: "Sewing", emoji: "🧶" },
    { text: "Shoes", emoji: "👞" },
    { text: "Shooting guns", emoji: "💥" },
    { text: "Shooting sport", emoji: "💥" },
    { text: "Shopping", emoji: "🛍️" },
    { text: "Singing", emoji: "🎤" },
    { text: "Skate Boarding", emoji: "⛸️" },
    { text: "Sketching", emoji: "✏️" },
    { text: "Skiing", emoji: "🎿" },
    { text: "Skincare", emoji: "🥒" },
    { text: "Sky Diving", emoji: "👟" },
    { text: "Sleeping", emoji: "😴" },
    { text: "Snooker", emoji: "🎱" },
    { text: "Snorkeling", emoji: "🤿" },
    { text: "Soap Making", emoji: "🧼" },
    { text: "Soccer", emoji: "⚽" },
    { text: "Sports", emoji: "🏅" },
    { text: "Stocks", emoji: "📈" },
    { text: "Storytelling", emoji: "📖" },
    { text: "Sudoku Puzzles", emoji: "🧩" },
    { text: "Surfing", emoji: "🌊" },
    { text: "Swimming", emoji: "🌊" },
    { text: "Table Tennis", emoji: "🎾" },
    { text: "Table football", emoji: "🏈" },
    { text: "Taekwondo", emoji: "🥋" },
    { text: "Tai chi", emoji: "🥋" },
    { text: "Tango Dance", emoji: "💃🏽" },
    { text: "Tarot", emoji: "🃏" },
    { text: "Ten Pin Bowling", emoji: "🎳" },
    { text: "Tennis", emoji: "🎾" },
    { text: "Traveling", emoji: "🚗" },
    { text: "Treasure Hunting", emoji: "💎" },
    { text: "Tutoring", emoji: "📔" },
    { text: "Vehicle restoration", emoji: "🚗" },
    { text: "Video", emoji: "🎬" },
    { text: "Video Games", emoji: "🎮" },
    { text: "Violin", emoji: "🎻" },
    { text: "Volunteering", emoji: "📌" },
    { text: "Walking", emoji: "👟" },
    { text: "Wall Art", emoji: "🎨" },
    { text: "War games", emoji: "🎮" },
    { text: "Watching Movies", emoji: "🎬" },
    { text: "Watching Sports", emoji: "🏅" },
    { text: "Watching TV", emoji: "📺" },
    { text: "Weather Forecasting", emoji: "🌧️" },
    { text: "Web surfing", emoji: "🌐" },
    { text: "Websites", emoji: "🌐" },
    { text: "Weight training", emoji: "🏋‍♀️" },
    { text: "Weight lifting", emoji: "🏋‍♀️" },
    { text: "Wildlife Photography", emoji: "📷" },
    { text: "Wine Making", emoji: "🍷" },
    { text: "Wines", emoji: "🍷" },
    { text: "Wood Carving", emoji: "🌲" },
    { text: "World news ", emoji: "🗞️" },
    { text: "Politics", emoji: "🗞️" },
    { text: "Wrestling", emoji: "🥋" },
    { text: "Writing", emoji: "🖋️" },
    { text: "Writing Music", emoji: "🎵" },
    { text: "Songwriting", emoji: "🎵" },
    { text: "Yachting", emoji: "⛵" },
    { text: "Yoga", emoji: "🧘🏻‍♀️" },
    { text: "Youth Band", emoji: "🎵" },
    { text: "Zumba", emoji: "👟" },
    { text: "Cooperative games", emoji: "🕹️" },
    { text: "Courses", emoji: "📕" },
    { text: "Diving", emoji: "🤿" },
    { text: "Pets", emoji: "🐩" },
    { text: "Strategy games", emoji: "🕹️" },
  ];
  
  
export const searchHobbies = (word="") => {
    return Hobbies.filter(hobby => hobby.text.toLowerCase().search(word.toLowerCase()) !== -1)
}